#image: maven:

stages:
  - build
  - test
  - deploy
  - deploy-prod

build:
  image: maven:3-jdk-8
  stage: build
  tags:
    - dalfcs_gitlab_docker_ci
  script:
    - mvn $MAVEN_CLI_OPTS compile
    #- ls
  artifacts:
    paths:
      - target/*.jar
  only:
    refs:
      - main
      - release
  #     - test
test:
  image: maven:3-jdk-8
  stage: test
  tags:
    - dalfcs_gitlab_docker_ci
  script:
    - mvn clean test
  artifacts:
    when: always
      #reports:
      #junit:
      #- target/surefire-reports/TEST-*.xml
    #- target/failsafe-reports/TEST-*.xml
  only:
    refs:
      - main
      - release
  #    - test

deploy-prod:
  image: ruby:latest
  stage: deploy
  tags:
    - dalfcs_gitlab_docker_ci
  #   before_script:
  #     - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
  #      - eval $(ssh-agent -s)
  #     - echo "$DEPLOY_SSH_KEY" | tr -d '\r' | ssh-add -
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
  #   #TODO: Add Production App Environment Variables
  only:
    - main

deploy:
  image: ruby:latest
  stage: deploy
  tags:
    - dalfcs_gitlab_docker_ci
  #  before_script:
  #     - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
  #     - eval $(ssh-agent -s)
  #     - echo "$DEPLOY_SSH_KEY" | tr -d '\r' | ssh-add -
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME_DEV --api-key=$HEROKU_API_KEY
  only:
    - develop

deploy-release:
  image: ruby:latest
  stage: deploy
  tags:
    - dalfcs_gitlab_docker_ci
  #  before_script:
  #     - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
  #     - eval $(ssh-agent -s)
  #     - echo "$DEPLOY_SSH_KEY" | tr -d '\r' | ssh-add -
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME_RELEASE --api-key=$HEROKU_API_KEY
  only:
    - release    