server:
  port: 8990

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: CSCI5308_9_TEST_USER
    url: jdbc:mysql://db-5308.cs.dal.ca:3306/CSCI5308_9_TEST?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    password: r2kZ3PzaUb
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
logging:
  level:
    org:
      hibernate: INFO
      springframework:
        web: DEBUG